import { Link, useNavigate, useSearch } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, BadgeCheck, Bell, Check, ChevronRight, CircleHelp, CreditCard, Heart, MapPin, Minus, Package, Plus, Search, ShieldCheck, SlidersHorizontal, Star, Store, Truck, UserRound } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { categories, formatNaira, products } from "../lib/catalog";
import { useShop } from "../lib/shop-context";
import { ProductCard, SearchBar, SectionTitle, TrustStrip } from "./marketplace";

const wrap = "mx-auto w-full max-w-[1440px] px-4 py-10 md:px-8 md:py-16";
const primary = "inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-brand px-6 text-sm font-bold text-brand-foreground transition hover:bg-brand/85 active:scale-[.98]";
const secondary = "inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-border bg-surface px-6 text-sm font-bold transition hover:bg-surface-muted active:scale-[.98]";

export function ListingPage({ category, query }: { category?: string; query?: string }) {
  const [sort, setSort] = useState("recommended");
  const [verifiedOnly, setVerifiedOnly] = useState(false);
  const filtered = useMemo(() => products.filter((product) => {
    const categoryMatch = !category || category === "all" || product.category.toLowerCase() === category.toLowerCase();
    const queryMatch = !query || query === "all" || `${product.name} ${product.category} ${product.seller}`.toLowerCase().includes(query.toLowerCase());
    return categoryMatch && queryMatch;
  }).sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : b.rating - a.rating), [category, query, sort]);
  const heading = query && query !== "all" ? `Results for “${query}”` : category && category !== "all" ? category : "Explore the marketplace";
  return <div className={wrap}>
    <div className="mb-8 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase text-brand-strong">Shop JustBay</p><h1 className="font-display text-4xl font-extrabold md:text-6xl">{heading}</h1><p className="mt-4 text-muted-foreground">Trusted products from verified sellers across Eastern Nigeria.</p></div>
    <div className="mb-6 md:hidden"><SearchBar /></div>
    <div className="grid gap-8 lg:grid-cols-[240px_minmax(0,1fr)]">
      <aside className="hidden lg:block"><div className="sticky top-28 rounded-[1.5rem] bg-surface p-6"><h2 className="font-display text-lg font-bold">Filters</h2><div className="mt-6 space-y-6 text-sm"><FilterGroup title="Category" items={categories} /><FilterGroup title="Location" items={["Awka", "Onitsha", "Enugu", "Owerri", "Aba"]} /><label className="flex items-center gap-3"><input type="checkbox" checked={verifiedOnly} onChange={(event) => setVerifiedOnly(event.target.checked)} className="size-4 accent-brand-strong" /> Verified sellers only</label><FilterGroup title="Delivery" items={["Same day", "This week"]} /></div></div></aside>
      <section><div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><p className="min-w-0 text-sm text-muted-foreground">{filtered.length} products {verifiedOnly && "from verified sellers"}</p><div className="flex gap-2"><button className="grid size-11 place-items-center rounded-full border border-border bg-surface lg:hidden" aria-label="Open filters"><SlidersHorizontal className="size-4" /></button><select aria-label="Sort products" value={sort} onChange={(event) => setSort(event.target.value)} className="h-11 rounded-full border border-border bg-surface px-4 text-sm font-semibold"><option value="recommended">Recommended</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></div></div>
        {filtered.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-8 sm:gap-x-5 md:grid-cols-3 xl:grid-cols-4">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="rounded-[2rem] bg-surface p-12 text-center"><Search className="mx-auto size-8 text-muted-foreground" /><h2 className="mt-4 font-display text-2xl font-bold">No exact matches</h2><p className="mt-2 text-sm text-muted-foreground">Try a broader search or explore all categories.</p><Link to="/products" className={`${primary} mt-6`}>Browse all products</Link></div>}
      </section>
    </div>
  </div>;
}

function FilterGroup({ title, items }: { title: string; items: string[] }) { return <fieldset><legend className="mb-3 font-bold">{title}</legend><div className="space-y-2">{items.map((item) => <label key={item} className="flex items-center gap-3 text-muted-foreground"><input type="checkbox" className="size-4 accent-brand-strong" /> {item}</label>)}</div></fieldset>; }

export function ProductPage({ id }: { id: string }) {
  const product = products.find((item) => item.id === id) ?? products[0];
  const [quantity, setQuantity] = useState(1);
  const { addToCart, wishlist, toggleWishlist } = useShop();
  const navigate = useNavigate();
  return <div className={wrap}>
    <nav className="mb-8 flex items-center gap-2 text-sm text-muted-foreground"><Link to="/products">Products</Link><ChevronRight className="size-3" /><span className="truncate">{product.name}</span></nav>
    <div className="grid gap-10 lg:grid-cols-2 lg:gap-16">
      <div className="grid gap-3 sm:grid-cols-[84px_minmax(0,1fr)]"><div className="order-2 flex gap-3 sm:order-1 sm:flex-col">{[1,2,3].map((index) => <button key={index} className="aspect-square w-20 overflow-hidden rounded-2xl border border-border bg-surface-muted"><img src={product.image} alt="" loading="lazy" width={120} height={120} className="h-full w-full object-cover" /></button>)}</div><div className="order-1 aspect-square overflow-hidden rounded-[2rem] bg-surface-muted sm:order-2"><img src={product.image} alt={product.name} width={768} height={768} className="h-full w-full object-cover" /></div></div>
      <div className="self-center"><p className="text-sm font-bold text-brand-strong">{product.category} · {product.city}</p><h1 className="mt-3 font-display text-4xl font-extrabold md:text-6xl">{product.name}</h1><div className="mt-4 flex items-center gap-2 text-sm"><Star className="size-4 fill-warning text-warning" /><b>{product.rating}</b><span className="text-muted-foreground">{product.reviews} verified reviews</span></div><div className="mt-7 flex items-baseline gap-3"><span className="font-display text-3xl font-extrabold">{formatNaira(product.price)}</span>{product.oldPrice && <span className="text-muted-foreground line-through">{formatNaira(product.oldPrice)}</span>}</div>
        <div className="my-7 rounded-[1.5rem] bg-surface p-5"><p className="flex items-center gap-2 font-bold"><BadgeCheck className="size-5 text-success" /> JustBay Verified</p><p className="mt-1 text-sm text-muted-foreground">Sold by {product.seller} · {product.city}</p><p className="mt-4 flex items-center gap-2 text-sm"><Truck className="size-4 text-accent" /> {product.delivery} to Awka</p></div>
        <div className="flex flex-wrap gap-3"><div className="flex h-12 items-center rounded-full border border-border bg-surface"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity" className="grid size-12 place-items-center"><Minus className="size-4" /></button><span className="w-8 text-center font-bold">{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity" className="grid size-12 place-items-center"><Plus className="size-4" /></button></div><button onClick={() => addToCart(product.id, quantity)} className={primary}>Add to cart <ArrowRight className="size-4" /></button><button onClick={() => { addToCart(product.id, quantity); void navigate({ to: "/checkout" }); }} className={secondary}>Buy now</button><button onClick={() => toggleWishlist(product.id)} aria-label="Toggle wishlist" className="grid size-12 place-items-center rounded-full border border-border bg-surface"><Heart className={`size-5 ${wishlist.includes(product.id) ? "fill-accent text-accent" : ""}`} /></button></div>
        <div className="mt-8 grid grid-cols-2 gap-3 text-xs text-muted-foreground sm:grid-cols-4">{[[ShieldCheck,"Secure payment"],[Truck,"Tracked delivery"],[BadgeCheck,"Verified seller"],[ArrowLeft,"Easy returns"]].map(([Icon,label]) => <div key={String(label)}><Icon className="mb-2 size-5 text-foreground" />{String(label)}</div>)}</div>
      </div>
    </div>
    <section className="py-20"><div className="grid gap-10 border-t border-border pt-10 md:grid-cols-3"><div><p className="text-xs font-bold uppercase text-muted-foreground">Product details</p><h2 className="mt-3 font-display text-3xl font-bold">Made for everyday life.</h2></div><p className="text-muted-foreground md:col-span-2">A carefully selected marketplace product backed by a verified local seller. Every listing includes clear pricing, local delivery estimates and JustBay buyer protection.</p></div></section>
    <SectionTitle eyebrow="You may also like" title="Related products" /><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{products.filter((item) => item.id !== product.id).slice(0,4).map((item) => <ProductCard key={item.id} product={item} />)}</div>
  </div>;
}

export function CartPage() {
  const { cart, updateQuantity } = useShop(); const items = products.filter((product) => cart[product.id]); const subtotal = items.reduce((sum, product) => sum + product.price * cart[product.id], 0); const delivery = items.length ? 2000 : 0;
  return <div className={wrap}><h1 className="font-display text-4xl font-extrabold md:text-6xl">Your cart</h1><p className="mt-3 text-muted-foreground">Review your items before checkout.</p><div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_380px]"><section className="space-y-3">{items.length ? items.map((product) => <article key={product.id} className="grid grid-cols-[88px_minmax(0,1fr)] gap-4 rounded-[1.5rem] bg-surface p-4 sm:grid-cols-[112px_minmax(0,1fr)_auto]"><img src={product.image} alt={product.name} width={160} height={160} className="aspect-square rounded-2xl object-cover" /><div className="min-w-0"><p className="text-xs text-muted-foreground">{product.seller}</p><h2 className="mt-1 truncate font-display font-bold">{product.name}</h2><p className="mt-2 font-bold">{formatNaira(product.price)}</p><button onClick={() => updateQuantity(product.id, 0)} className="mt-3 text-xs font-semibold text-muted-foreground underline">Remove</button></div><div className="col-span-2 flex h-11 items-center justify-self-start rounded-full border border-border sm:col-span-1 sm:self-center"><button onClick={() => updateQuantity(product.id, cart[product.id]-1)} className="grid size-10 place-items-center"><Minus className="size-4" /></button><span className="w-6 text-center text-sm font-bold">{cart[product.id]}</span><button onClick={() => updateQuantity(product.id, cart[product.id]+1)} className="grid size-10 place-items-center"><Plus className="size-4" /></button></div></article>) : <div className="rounded-[2rem] bg-surface p-12 text-center"><Package className="mx-auto size-8" /><h2 className="mt-4 font-display text-2xl font-bold">Your cart is empty</h2><Link to="/products" className={`${primary} mt-6`}>Start shopping</Link></div>}</section><OrderSummary subtotal={subtotal} delivery={delivery} checkout={items.length > 0} /></div></div>;
}

function OrderSummary({ subtotal, delivery, checkout }: { subtotal: number; delivery: number; checkout?: boolean }) { return <aside className="h-fit rounded-[2rem] bg-dark p-7 text-dark-foreground"><h2 className="font-display text-2xl font-bold">Order summary</h2><div className="mt-6 space-y-3 text-sm text-dark-foreground/65"><p className="flex justify-between"><span>Subtotal</span><b className="text-dark-foreground">{formatNaira(subtotal)}</b></p><p className="flex justify-between"><span>Delivery</span><b className="text-dark-foreground">{formatNaira(delivery)}</b></p></div><div className="my-5 border-t border-dark-foreground/15" /><p className="flex justify-between font-display text-xl font-bold"><span>Total</span><span>{formatNaira(subtotal + delivery)}</span></p>{checkout && <Link to="/checkout" className={`${primary} mt-7 w-full`}>Proceed to checkout <ArrowRight className="size-4" /></Link>}<p className="mt-4 text-center text-xs text-dark-foreground/50">Buyer protection included</p></aside>; }

export function CheckoutPage() {
  const { cart } = useShop(); const navigate = useNavigate(); const items = products.filter((product) => cart[product.id]); const subtotal = items.reduce((sum, product) => sum + product.price * cart[product.id], 0); const [delivery, setDelivery] = useState("standard"); const [payment, setPayment] = useState("transfer");
  const submit = (event: FormEvent) => { event.preventDefault(); void navigate({ to: "/order-confirmation" }); };
  return <form onSubmit={submit} className={wrap}><Link to="/cart" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4" /> Back to cart</Link><h1 className="font-display text-4xl font-extrabold md:text-6xl">Checkout</h1><div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-5"><CheckoutSection number="01" title="Delivery address"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" placeholder="Chinedu Okafor" /><Field label="Phone number" placeholder="0800 000 0000" /><SelectField label="State" options={["Anambra","Enugu","Imo","Abia","Ebonyi"]} /><Field label="City" placeholder="Awka" /><Field label="Area" placeholder="Ifite" /><Field label="Street" placeholder="Street name" /><Field label="House / building" placeholder="Building or compound" /><Field label="Landmark" placeholder="Near UNIZIK Junction" /><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Delivery instructions</span><textarea className="min-h-24 w-full rounded-2xl border border-border bg-surface-muted p-4 outline-none" placeholder="Helpful directions for the rider" /></label></div></CheckoutSection><CheckoutSection number="02" title="Delivery method"><Choice value="standard" selected={delivery} onSelect={setDelivery} title="Standard delivery" copy="2–4 business days" price="₦2,000" /><Choice value="express" selected={delivery} onSelect={setDelivery} title="Express delivery" copy="Next business day" price="₦4,500" /><Choice value="pickup" selected={delivery} onSelect={setDelivery} title="Pickup point" copy="Collect in Awka" price="Free" /></CheckoutSection><CheckoutSection number="03" title="Payment"><Choice value="transfer" selected={payment} onSelect={setPayment} title="Bank transfer" copy="Transfer after placing your order" icon={<CreditCard className="size-5" />} /><Choice value="card" selected={payment} onSelect={setPayment} title="Card" copy="Visa, Mastercard or Verve" icon={<CreditCard className="size-5" />} /><Choice value="ussd" selected={payment} onSelect={setPayment} title="USSD" copy="Pay securely from your phone" icon={<CreditCard className="size-5" />} /></CheckoutSection></div><div><OrderSummary subtotal={subtotal || products[2].price} delivery={delivery === "pickup" ? 0 : delivery === "express" ? 4500 : 2000} /><button type="submit" className={`${primary} mt-4 w-full`}>Place demo order <ArrowRight className="size-4" /></button><p className="mt-3 text-center text-xs text-muted-foreground">No real payment will be taken.</p></div></div></form>;
}

function CheckoutSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="rounded-[2rem] bg-surface p-5 md:p-8"><div className="mb-6 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-brand text-xs font-extrabold">{number}</span><h2 className="font-display text-2xl font-bold">{title}</h2></div>{children}</section>; }
function Field({ label, placeholder }: { label: string; placeholder: string }) { return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input required className="h-13 w-full rounded-2xl border border-transparent bg-surface-muted px-4 outline-none focus:border-brand-strong" placeholder={placeholder} /></label>; }
function SelectField({ label, options }: { label: string; options: string[] }) { return <label><span className="mb-2 block text-sm font-semibold">{label}</span><select className="h-13 w-full rounded-2xl border border-transparent bg-surface-muted px-4 outline-none">{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function Choice({ value, selected, onSelect, title, copy, price, icon }: { value:string; selected:string; onSelect:(value:string)=>void; title:string; copy:string; price?:string; icon?:React.ReactNode }) { const active = value === selected; return <button type="button" onClick={() => onSelect(value)} className={`mb-3 grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border p-4 text-left ${active ? "border-brand-strong bg-brand/10" : "border-border"}`}><span className={`grid size-6 place-items-center rounded-full border ${active ? "border-brand-strong bg-brand" : "border-border"}`}>{active && <Check className="size-3" />}</span><span className="min-w-0">{icon}<b className="block">{title}</b><small className="text-muted-foreground">{copy}</small></span>{price && <b className="text-sm">{price}</b>}</button>; }

export function OrderConfirmationPage() { return <div className={`${wrap} text-center`}><div className="mx-auto grid size-20 place-items-center rounded-full bg-brand"><Check className="size-9" /></div><p className="mt-8 text-xs font-bold uppercase text-brand-strong">Order JB-24091</p><h1 className="mx-auto mt-3 max-w-3xl font-display text-4xl font-extrabold md:text-6xl">Your order is confirmed.</h1><p className="mx-auto mt-5 max-w-xl text-muted-foreground">The seller has received your order. This is a demo, so no payment was collected and no delivery will be made.</p><div className="mx-auto mt-10 max-w-3xl rounded-[2rem] bg-surface p-7 text-left"><OrderTimeline /></div><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/track-order" className={primary}>Track order</Link><Link to="/products" className={secondary}>Keep shopping</Link></div></div>; }
export function OrderTrackingPage() { return <div className={wrap}><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase text-brand-strong">Order JB-24091</p><h1 className="mt-3 font-display text-4xl font-extrabold md:text-6xl">On its way to Awka.</h1><div className="mt-8 rounded-[2rem] bg-surface p-6 md:p-9"><div className="mb-8 flex items-center gap-3"><Truck className="size-6 text-accent" /><div><b>Estimated delivery: Friday</b><p className="text-sm text-muted-foreground">Rider assignment pending</p></div></div><OrderTimeline /></div></div></div>; }
function OrderTimeline() { return <ol className="space-y-0">{["Order confirmed","Seller processing","Ready for pickup","Out for delivery","Delivered"].map((item,index) => <li key={item} className="grid grid-cols-[36px_minmax(0,1fr)] gap-3"><div className="flex flex-col items-center"><span className={`grid size-8 place-items-center rounded-full ${index < 2 ? "bg-brand" : index === 2 ? "border-2 border-brand-strong" : "border border-border"}`}>{index < 2 ? <Check className="size-4" /> : index+1}</span>{index < 4 && <span className="h-10 w-px bg-border" />}</div><div className="pt-1"><b className={index > 2 ? "text-muted-foreground" : ""}>{item}</b>{index === 1 && <p className="text-xs text-muted-foreground">ABC Electronics is packing your item</p>}</div></li>)}</ol>; }

export function AccountPage({ section = "overview" }: { section?: string }) {
  const nav = [[UserRound,"Account","/account"],[Package,"My orders","/orders"],[Heart,"Wishlist","/wishlist"],[MapPin,"Addresses","/addresses"],[Bell,"Notifications","/notifications"],[CircleHelp,"Help & support","/help"]] as const;
  return <div className={wrap}><h1 className="font-display text-4xl font-extrabold md:text-6xl">My JustBay</h1><div className="mt-10 grid gap-8 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="h-fit rounded-[1.5rem] bg-surface p-3">{nav.map(([Icon,label,to]) => <Link key={to} to={to} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold hover:bg-surface-muted"><Icon className="size-4" />{label}</Link>)}</aside><section><AccountContent section={section} /></section></div></div>;
}
function AccountContent({ section }: { section: string }) { const { wishlist } = useShop(); if (section === "wishlist") return <><SectionTitle title="My wishlist" /><div className="grid grid-cols-2 gap-4 md:grid-cols-3">{products.filter((item) => wishlist.includes(item.id)).map((item) => <ProductCard key={item.id} product={item} />)}{wishlist.length === 0 && <Empty title="Nothing saved yet" copy="Tap the heart on any product to keep it here." />}</div></>; if (section === "orders") return <><SectionTitle title="My orders" /><div className="rounded-[1.5rem] bg-surface p-5"><p className="text-xs text-muted-foreground">Order JB-24091 · Today</p><div className="mt-3 flex items-center justify-between"><b>Airwave Pro Headphones</b><span className="rounded-full bg-brand/20 px-3 py-1 text-xs font-bold">Processing</span></div><Link to="/track-order" className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Track order <ArrowRight className="size-4" /></Link></div></>; if (section === "addresses") return <><SectionTitle title="Saved addresses" /><div className="rounded-[1.5rem] bg-surface p-6"><b>Home</b><p className="mt-2 text-sm text-muted-foreground">Ifite, near UNIZIK Junction<br/>Awka, Anambra State</p></div></>; if (section === "notifications") return <><SectionTitle title="Notifications" /><Empty title="You’re all caught up" copy="Order and deal updates will appear here." /></>; if (section === "help") return <><SectionTitle title="How can we help?" /><div className="grid gap-3 sm:grid-cols-2">{["Track an order","Returns & refunds","Payments","Talk to support"].map((item) => <button key={item} className="flex min-h-16 items-center justify-between rounded-2xl bg-surface p-5 text-left font-bold">{item}<ArrowRight className="size-4" /></button>)}</div></>; return <><SectionTitle eyebrow="Good afternoon" title="Welcome back, Chinedu" /><div className="grid gap-4 sm:grid-cols-3">{[[Package,"1","Active order"],[Heart,String(wishlist.length),"Saved items"],[MapPin,"1","Saved address"]].map(([Icon,value,label]) => <div key={String(label)} className="rounded-[1.5rem] bg-surface p-6"><Icon className="size-5 text-brand-strong" /><p className="mt-6 font-display text-3xl font-bold">{String(value)}</p><p className="text-sm text-muted-foreground">{String(label)}</p></div>)}</div></>; }
function Empty({ title, copy }: { title:string; copy:string }) { return <div className="col-span-full rounded-[1.5rem] bg-surface p-10 text-center"><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{copy}</p></div>; }

export function AuthPage({ mode }: { mode: "login" | "register" | "forgot" }) { const navigate = useNavigate(); const submit = (event: FormEvent) => { event.preventDefault(); void navigate({ to: "/account" }); }; const title = mode === "login" ? "Welcome back" : mode === "register" ? "Create your account" : "Reset your password"; return <div className={`${wrap} grid min-h-[70vh] place-items-center`}><form onSubmit={submit} className="w-full max-w-md rounded-[2rem] bg-surface p-6 md:p-9"><p className="text-xs font-bold uppercase text-brand-strong">JustBay account</p><h1 className="mt-3 font-display text-3xl font-extrabold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">Demo access only — no account is created.</p>{mode === "register" && <div className="mt-7"><Field label="Full name" placeholder="Your name" /></div>}<div className={mode === "register" ? "mt-4" : "mt-7"}><Field label="Email or phone" placeholder="you@example.com" /></div>{mode !== "forgot" && <div className="mt-4"><Field label="Password" placeholder="Enter password" /></div>}<button className={`${primary} mt-6 w-full`}>{mode === "forgot" ? "Send reset link" : mode === "register" ? "Create demo account" : "Sign in"}</button><div className="mt-6 flex justify-between text-sm">{mode === "login" ? <><Link to="/forgot-password">Forgot password?</Link><Link to="/register" className="font-bold">Create account</Link></> : <Link to="/login" className="font-bold">Back to sign in</Link>}</div></form></div>; }

export function StoresPage() { return <div className={wrap}><p className="text-xs font-bold uppercase text-brand-strong">Local commerce</p><h1 className="mt-3 font-display text-4xl font-extrabold md:text-6xl">Trusted sellers near you.</h1><div className="mt-10 grid gap-4 md:grid-cols-3">{[["ABC Electronics","Awka","4.9","120"],["Nwaanyị Styles","Onitsha","4.8","86"],["Amara Beauty Room","Enugu","4.7","64"]].map(([name,city,rating,count]) => <article key={name} className="rounded-[2rem] bg-surface p-7"><div className="grid size-14 place-items-center rounded-2xl bg-brand font-display text-xl font-extrabold">{name[0]}</div><div className="mt-8 flex items-center gap-2"><h2 className="font-display text-xl font-bold">{name}</h2><BadgeCheck className="size-4 text-success" /></div><p className="mt-2 text-sm text-muted-foreground"><MapPin className="mr-1 inline size-3" />{city} · {count} products</p><p className="mt-4 text-sm"><Star className="mr-1 inline size-4 fill-warning text-warning" />{rating}</p></article>)}</div></div>; }

export { TrustStrip };